# Generated by Django 4.2.1 on 2023-05-17 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_pacjenta', models.CharField(max_length=30)),
                ('gatunek', models.CharField(choices=[('pies', 'Pies'), ('kot', 'Kot'), ('królik', 'Królik'), ('świnka morska', 'Świnka Morska'), ('chomik', 'Chomik')], default='pies', max_length=20)),
                ('data_urodzenia', models.DateField(max_length=30)),
                ('wiek', models.IntegerField()),
                ('plec', models.CharField(choices=[('samiec', 'Samiec'), ('samica', 'Samica')], default='samica', max_length=30)),
                ('telfon', models.CharField(default='Brak danych', max_length=9)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('imie_własciciela', models.CharField(default='Brak danych', max_length=60)),
                ('nazwisko_własciciela', models.CharField(max_length=100)),
                ('adres', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rachunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lekarza', models.IntegerField()),
                ('id_pacjenta', models.IntegerField()),
                ('data_wystawienia', models.CharField(max_length=30)),
                ('cena_uslugi', models.IntegerField()),
                ('diagnoza', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_lekarza', models.CharField(default='Brak danych', max_length=50)),
                ('nazwisko_lekarza', models.CharField(default='Brak danych', max_length=70)),
                ('id_lekarza', models.IntegerField()),
                ('nr_telefonu', models.CharField(default='Brak danych', max_length=9)),
                ('pwzNumer', models.IntegerField()),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pacjent')),
            ],
        ),
    ]
