# Generated by Django 4.2.1 on 2023-05-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lekarz',
            name='imie_lekarza',
        ),
        migrations.RemoveField(
            model_name='lekarz',
            name='nazwisko_lekarza',
        ),
        migrations.RemoveField(
            model_name='lekarz',
            name='nr_telefonu',
        ),
    ]
