# Generated by Django 4.2.1 on 2023-05-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_lekarze'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weterynarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_weterynarza', models.CharField(max_length=50)),
                ('nazwisko_weterynarza', models.CharField(max_length=100)),
            ],
        ),
    ]
