# Generated by Django 4.2.1 on 2023-05-18 08:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_weterynarz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacjenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_pacjenta', models.CharField(max_length=30)),
                ('gatunek', models.CharField(choices=[('pies', 'Pies'), ('kot', 'Kot'), ('królik', 'Królik'), ('świnka morska', 'Świnka Morska'), ('chomik', 'Chomik')], default='pies', max_length=20)),
                ('data_urodzenia', models.DateField(max_length=30)),
                ('plec', models.CharField(choices=[('samiec', 'Samiec'), ('samica', 'Samica')], default='samica', max_length=30)),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('imie_własciciela', models.CharField(default='Brak danych', max_length=60)),
                ('nazwisko_własciciela', models.CharField(max_length=100)),
                ('adres', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rachunki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wystawienia', models.CharField(max_length=30)),
                ('cena_uslugi', models.IntegerField()),
                ('diagnoza', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='lekarze',
            name='pacjent',
        ),
        migrations.RemoveField(
            model_name='lekarze',
            name='rachunek',
        ),
        migrations.AddField(
            model_name='weterynarz',
            name='pwzNumer',
            field=models.CharField(default='Brak danych', max_length=5),
        ),
        migrations.AddField(
            model_name='weterynarz',
            name='telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(default='Brak danych', max_length=128, region=None),
        ),
        migrations.DeleteModel(
            name='Lekarz',
        ),
        migrations.DeleteModel(
            name='Lekarze',
        ),
        migrations.DeleteModel(
            name='Pacjent',
        ),
        migrations.DeleteModel(
            name='Rachunek',
        ),
    ]
