# Generated by Django 4.2.1 on 2023-05-20 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_pacjenci_options_rachunki_pacjent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rachunki',
            name='pacjent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.pacjenci'),
        ),
        migrations.AlterField(
            model_name='rachunki',
            name='weterynarz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.weterynarz'),
        ),
    ]
