# Generated by Django 4.2.1 on 2023-05-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_rachunki_pacjent_alter_rachunki_weterynarz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rachunki',
            old_name='pacjent',
            new_name='pacjent1',
        ),
    ]
