# Generated by Django 4.2.1 on 2023-05-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_pacjent_remove_rachunki_pacjent1_rachunki_pacjent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjent',
            name='imie_własciciela',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
