# Generated by Django 4.2.1 on 2023-05-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_rachunek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rachunki',
            name='pacjent',
        ),
        migrations.RemoveField(
            model_name='rachunki',
            name='weterynarz',
        ),
        migrations.DeleteModel(
            name='Pacjent',
        ),
        migrations.DeleteModel(
            name='Rachunki',
        ),
    ]
