# Generated by Django 4.2.1 on 2023-05-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_rachunki_pacjent_remove_rachunki_weterynarz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rachunek',
            name='plik_dicom',
            field=models.FileField(blank=True, null=True, upload_to='static/dicom'),
        ),
    ]
